server:
  port: 8552
  servlet:
    context-path: /admin-api


spring:
    profiles:
      active: dev
    http:
      encoding:
        charset: UTF-8
        force: true
        enabled: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml